/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import com.formdev.flatlaf.FlatClientProperties;
import controlador.bd.Crud;
import controlador.bd.Sql2;
import controlador.user.ControladorTabla;
import controlador.user.ControladorVentana;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import modelo.Alumno;

/**
 *
 * @author shelb
 */
public class RegistroAlumnos extends javax.swing.JFrame {


    Alumno alumno;
    private int id_seleccionado;
    Alumnos alumnos = new Alumnos();
    public RegistroAlumnos() {
        initComponents();
        estiloBuscador();
        this.setExtendedState(6);
        ControladorVentana.ExitConfirmation(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        la = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        l = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnActualizarAl = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de alumnos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 0, 12), new java.awt.Color(17, 152, 85))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(17, 152, 85));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(17, 152, 85));
        jLabel1.setText("Apellido:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 80, 24));

        la.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        la.setForeground(new java.awt.Color(17, 152, 85));
        la.setText("Correo:");
        jPanel2.add(la, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, 20));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(17, 152, 85));
        jLabel2.setText("Telefono:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 85, 24));

        l.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        l.setForeground(new java.awt.Color(17, 152, 85));
        l.setText("Edad");
        jPanel2.add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEdadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });
        jPanel2.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 90, 40));

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel2.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 370, 40));

        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 370, 40));

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        jPanel2.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 370, 40));

        btnAgregar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(17, 152, 85));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Inventarios.png"))); // NOI18N
        btnAgregar.setText("Registrar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 170, 50));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 370, 40));

        jLabel6.setBackground(new java.awt.Color(17, 152, 85));
        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(17, 152, 85));
        jLabel6.setText("Nombre:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 80, 24));

        btnLimpiar.setForeground(new java.awt.Color(17, 152, 85));
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/broom2.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 170, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 610, 540));

        jPanel4.setBackground(new java.awt.Color(17, 152, 85));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setForeground(new java.awt.Color(17, 152, 85));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salida.png"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel4.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 200, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 30));

        jLabel5.setBackground(new java.awt.Color(0, 51, 153));
        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(17, 152, 85));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/libro.png"))); // NOI18N
        jLabel5.setText("Registro de alumnos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 650, 90));

        btnActualizarAl.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnActualizarAl.setForeground(new java.awt.Color(17, 152, 85));
        btnActualizarAl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Inventarios.png"))); // NOI18N
        btnActualizarAl.setText("Modificar datos");
        btnActualizarAl.setActionCommand("");
        btnActualizarAl.setEnabled(false);
        btnActualizarAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarAlActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizarAl, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 370, 170, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:

        Alumnos nef = new Alumnos();
        nef.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:

        if (this.txtNombre.getText().isEmpty() || this.txtApellido.getText().isEmpty()
                || this.txtDireccion.getText().isEmpty()
                || this.txtTelefono.getText().isEmpty()
                || this.txtEdad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor complete todos los campos", "Campos en blanco", JOptionPane.INFORMATION_MESSAGE);
        } else {

            Alumno alumno = new Alumno();

            alumno.setNombre(this.txtNombre.getText());

//            String posicion = (String) comboCat.getSelectedItem();
//            alumno.setCategoriaLibro(posicion);
            alumno.setApellido(this.txtApellido.getText());
            alumno.setCorreo(this.txtDireccion.getText());
            alumno.setTelefono(this.txtTelefono.getText());
            int edad = Integer.parseInt(this.txtEdad.getText());
            alumno.setEdad(edad);

            
            Crud crud = new Crud();

            boolean resultado = crud.insertar(Sql2.insertarAlumno(alumno));

            if (resultado) {

                JOptionPane.showMessageDialog(null, "Alumno registrado", "Alumno", 1);

            } else {

                JOptionPane.showMessageDialog(null, "Ocurrio un error", "Error", 2);
            }

        }

        if (evt.getSource() == this.btnAgregar) {
            this.txtNombre.setText("");
            this.txtApellido.setText("");
            this.txtDireccion.setText("");
            this.txtTelefono.setText("");
            this.txtTelefono.setText("");

        }


    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped

        if (this.txtNombre.getText().length() >= 30) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Limite de caracteres alcanzado", "Longitud de caracteres", JOptionPane.INFORMATION_MESSAGE);

        }

        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();

            JOptionPane.showMessageDialog(null, "No puede ingresar números", "Tipo de entrada", JOptionPane.WARNING_MESSAGE);

        }

    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        // TODO add your handling code here:

        if (this.txtApellido.getText().length() >= 65) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Limite de caracteres alcanzado", "Longitud de caracteres", JOptionPane.INFORMATION_MESSAGE);

        }

        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();

            JOptionPane.showMessageDialog(null, "No puede ingresar números", "Tipo de entrada", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        // TODO add your handling code here:

        if (this.txtDireccion.getText().length() >= 30) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Limite de caracteres alcanzado", "Longitud de caracteres", JOptionPane.INFORMATION_MESSAGE);

        }

    }//GEN-LAST:event_txtDireccionKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:

        if (this.txtTelefono.getText().length() >= 10) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Limite de caracteres alcanzado", "Longitud de caracteres", JOptionPane.INFORMATION_MESSAGE);

        }

        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();

            JOptionPane.showMessageDialog(null, "No puede ingresar letras", "Tipo de entrada", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        // TODO add your handling code here:

        if (this.txtEdad.getText().length() >= 2) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Limite de caracteres alcanzado", "Longitud de caracteres", JOptionPane.INFORMATION_MESSAGE);

        }

        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();

            JOptionPane.showMessageDialog(null, "No puede ingresar letras", "Tipo de entrada", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_txtEdadKeyTyped

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtApellido.requestFocus();
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtDireccion.requestFocus();
        }
    }//GEN-LAST:event_txtApellidoKeyPressed

    private void txtDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtTelefono.requestFocus();
        }
    }//GEN-LAST:event_txtDireccionKeyPressed

    private void txtTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtEdad.requestFocus();
        }
    }//GEN-LAST:event_txtTelefonoKeyPressed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:

        if (evt.getSource() == btnLimpiar) {
            this.txtNombre.setText("");
            this.txtApellido.setText("");
            this.txtApellido.setText("");
            this.txtDireccion.setText("");
            this.txtTelefono.setText("");
            this.txtEdad.setText("");
        }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtEdadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnAgregar.doClick();
        }
    }//GEN-LAST:event_txtEdadKeyPressed

    private void btnActualizarAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarAlActionPerformed
if (this.txtNombre.getText().isEmpty() || this.txtApellido.getText().isEmpty() || this.txtDireccion.getText().isEmpty()
        || this.txtTelefono.getText().isEmpty() || this.txtEdad.getText().isEmpty()) {
    JOptionPane.showMessageDialog(null, "Por favor complete todos los campos", "Campos en blanco", JOptionPane.INFORMATION_MESSAGE);
} else {

    this.alumno = new Alumno();
    // Recogemos los datos 

    try {
        alumno.setNombre(this.txtNombre.getText());
        alumno.setApellido(this.txtApellido.getText());
        alumno.setCorreo(this.txtDireccion.getText());
        alumno.setTelefono(this.txtTelefono.getText());
        int edad = Integer.parseInt(this.txtEdad.getText());
        alumno.setEdad(edad);
        
        id_seleccionado = ControladorTabla.getInstance().getIdSeleccionado();
        alumno.setId_alumno(id_seleccionado);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Ingrese valores numéricos válidos para edad y teléfono", "Error de formato", JOptionPane.ERROR_MESSAGE);
        return;  // Sale del bloque de código si el input no es válido
    }

    // Preguntar si se desea guardar los cambios
    int opcion = JOptionPane.showConfirmDialog(null, 
        "¿Desea guardar los cambios?", 
        "Confirmar actualización", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE);

    if (opcion == JOptionPane.YES_OPTION) {
        Crud crud = new Crud();

        // ACTUALIZAR EN LA BD
        boolean resultado = crud.actualizarEliminar(Sql2.actualizarAlumno(alumno));

        if (resultado) {
            JOptionPane.showMessageDialog(null, "Datos del alumno actualizados correctamente", "Actualización", JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose();  // Cierra el formulario
            alumnos.mostrarAlumnos();
            Alumnos newframe = new Alumnos();
            newframe.setVisible(true);
            
        } else {
            JOptionPane.showMessageDialog(null, "No se actualizó correctamente", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        // Si no se quieren guardar los cambios
        JOptionPane.showMessageDialog(null, "Los cambios no han sido guardados.", "Aviso", JOptionPane.WARNING_MESSAGE);
    }
}


    }//GEN-LAST:event_btnActualizarAlActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarAl;
    public javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel l;
    private javax.swing.JLabel la;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtEdad;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    
    private void estiloBuscador(){
    
    txtNombre.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Nombre...");
    
     
    txtNombre.putClientProperty(FlatClientProperties.STYLE, ""
        + "arc:13;"
        + "borderWidth:0;"
        + "focusWidth:0;"
        + "innerFocusWidth:0;"
        + "margin:5,20,5,20;"
        + "background:$Panel.background");
    
    
    
        txtApellido.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Apellido...");
 
     
    txtApellido.putClientProperty(FlatClientProperties.STYLE, ""
        + "arc:13;"
        + "borderWidth:0;"
        + "focusWidth:0;"
        + "innerFocusWidth:0;"
        + "margin:5,20,5,20;"
        + "background:$Panel.background");
    
    
    
    
        txtDireccion.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Correo...");
    
     
    txtDireccion.putClientProperty(FlatClientProperties.STYLE, ""
        + "arc:13;"
        + "borderWidth:0;"
        + "focusWidth:0;"
        + "innerFocusWidth:0;"
        + "margin:5,20,5,20;"
        + "background:$Panel.background");
    
    txtTelefono.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Diez digitos...");
    
     
    txtTelefono.putClientProperty(FlatClientProperties.STYLE, ""
        + "arc:13;"
        + "borderWidth:0;"
        + "focusWidth:0;"
        + "innerFocusWidth:0;"
        + "margin:5,20,5,20;"
        + "background:$Panel.background");
    
    
    txtEdad.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "");
    
     
    txtEdad.putClientProperty(FlatClientProperties.STYLE, ""
        + "arc:13;"
        + "borderWidth:0;"
        + "focusWidth:0;"
        + "innerFocusWidth:0;"
        + "margin:5,20,5,20;"
        + "background:$Panel.background");
    
    
    btnAgregar.putClientProperty(FlatClientProperties.STYLE, ""
        +"hoverBackground: #119855;"
        +"hoverForeground: #00FFFF;");
}




}
