package gui;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import controlador.user.ControladorVentana;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.MediaTracker;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import javax.swing.JFrame;
import java.time.LocalTime;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class VentanaPrincipal extends javax.swing.JFrame {

    private Inventario inventario;

    public VentanaPrincipal() {
        
        
        initComponents();
        estiloBotones(btnAlumnos);
        configMensajeBienv();
        //gifRedimension();
        
        this.setTitle("Inicio");

        this.setExtendedState(MAXIMIZED_BOTH);
        ControladorVentana.ExitConfirmation(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        LSaludo = new javax.swing.JLabel();
        btnInventario = new javax.swing.JButton();
        btnAlumnos = new javax.swing.JButton();
        btnLibros = new javax.swing.JButton();
        btnDevLibro = new javax.swing.JButton();
        btnGuia = new javax.swing.JButton();
        btnPrestamos = new javax.swing.JButton();
        LBienvenida = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        LBienvenida1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(17, 152, 85));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 350, 80));

        jPanel4.setBackground(new java.awt.Color(17, 152, 85));
        jPanel4.setOpaque(false);

        LSaludo.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jPanel4.add(LSaludo);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 210, 40));

        btnInventario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnInventario.setForeground(new java.awt.Color(80, 144, 207));
        btnInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Inventarios.png"))); // NOI18N
        btnInventario.setText("  Inventario");
        btnInventario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventarioActionPerformed(evt);
            }
        });
        jPanel2.add(btnInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 50, 160, 50));

        btnAlumnos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnAlumnos.setForeground(new java.awt.Color(80, 144, 207));
        btnAlumnos.setText("    Alumnos");
        btnAlumnos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnosActionPerformed(evt);
            }
        });
        jPanel2.add(btnAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 160, 160, 50));

        btnLibros.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnLibros.setForeground(new java.awt.Color(80, 144, 207));
        btnLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registroli.png"))); // NOI18N
        btnLibros.setText("  Registro de Libro");
        btnLibros.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibrosActionPerformed(evt);
            }
        });
        jPanel2.add(btnLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 270, 160, 50));

        btnDevLibro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnDevLibro.setForeground(new java.awt.Color(80, 144, 207));
        btnDevLibro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prestamo.png"))); // NOI18N
        btnDevLibro.setText("Devolución de libro");
        btnDevLibro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDevLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevLibroActionPerformed(evt);
            }
        });
        jPanel2.add(btnDevLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 490, 160, 50));

        btnGuia.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnGuia.setForeground(new java.awt.Color(80, 144, 207));
        btnGuia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guia.png"))); // NOI18N
        btnGuia.setText("   Guia de usuario");
        btnGuia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiaActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 600, 160, 50));

        btnPrestamos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        btnPrestamos.setForeground(new java.awt.Color(80, 144, 207));
        btnPrestamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/prestamo.png"))); // NOI18N
        btnPrestamos.setText("    Prestamos");
        btnPrestamos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestamosActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 380, 160, 50));

        LBienvenida.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        LBienvenida.setText("Cerrar cesion");
        jPanel2.add(LBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 700, 130, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Conalep-logo.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 350, 200));

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-salida-48.png"))); // NOI18N
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 640, 70, 60));

        LBienvenida1.setFont(new java.awt.Font("Sitka Text", 1, 48)); // NOI18N
        LBienvenida1.setText("Bienvenido...");
        jPanel2.add(LBienvenida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 340, 90));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/biblio.jpg"))); // NOI18N
        jPanel2.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 750));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1370, 760);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnosActionPerformed
        // TODO add your handling code here:

        Alumnos newframe = new Alumnos();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAlumnosActionPerformed

    private void btnInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventarioActionPerformed
        // TODO add your handling code here:

        inventario = new Inventario();
        inventario.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnInventarioActionPerformed

    private void btnLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibrosActionPerformed
        // TODO add your handling code here:

        RegistroLibro newframe = new RegistroLibro();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLibrosActionPerformed

    private void btnDevLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevLibroActionPerformed
        // TODO add your handling code here:

        DevolucionLibro newframe = new DevolucionLibro();
        newframe.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_btnDevLibroActionPerformed

    private void btnGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiaActionPerformed
        // TODO add your handling code here:

        if (evt.getSource() == this.btnGuia) {

            try {
                //Ruta del archivo
                String filePath = "C:\\Users\\dell\\Documents\\ManualBiblionet\\ManualBiblionet.pdf";
                //Verificar si existe el archivo
                File file = new File(filePath);
                if (file.exists() && file.isFile()) {
                    Desktop.getDesktop().open(file);
                } else {
                    JOptionPane.showMessageDialog(null, "El archivo pdf no existe", "Archivo inexistente", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnGuiaActionPerformed

    private void btnPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestamosActionPerformed
        // TODO add your handling code here:

        Prestamos newframe = new Prestamos();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPrestamosActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed

        boolean logoutConfirmed = logOut(this);
        if (logoutConfirmed) {
            // Código para cerrar la sesión
            
            this.dispose(); // Esto cerrará la ventana de la aplicación

            // Mostrar la ventana de login
            Login loginFrame = new Login();
            loginFrame.setVisible(true);
        } else {
            // El usuario canceló el cierre de sesión
            
        }

    }//GEN-LAST:event_btnLogOutActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBienvenida;
    private javax.swing.JLabel LBienvenida1;
    private javax.swing.JLabel LSaludo;
    private javax.swing.JButton btnAlumnos;
    private javax.swing.JButton btnDevLibro;
    private javax.swing.JButton btnGuia;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnLibros;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnPrestamos;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    public void configMensajeBienv() {
        LocalTime horaLocal = LocalTime.now();
        String mensaje;

        if (horaLocal.isAfter(LocalTime.of(6, 0)) && horaLocal.isBefore(LocalTime.of(12, 0))) {
            mensaje = "Buenos dias!";
        } else if (horaLocal.isAfter(LocalTime.of(12, 0)) && horaLocal.isBefore(LocalTime.of(18, 0))) {
            mensaje = "Buenas tardes!";

        } else {
            mensaje = "Buenas noches!";
            
        }

        LSaludo.setForeground(Color.white);
        LSaludo.setText(mensaje);
        LSaludo.setVisible(true);
    }

    public static boolean logOut(JFrame frame) {
        int respuesta = JOptionPane.showConfirmDialog(frame,
                "¿Estás seguro de que quieres cerrar sesión?",
                "Confirmar Cierre de Sesión",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        return respuesta == JOptionPane.YES_OPTION;
    }
    
    
    private void estiloBotones(JButton button){
        
                button.putClientProperty(FlatClientProperties.STYLE, ""
        +"hoverBackground: #AAAAAA;");
        
//        btnAlumnos.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10)); // Margen interno
        
//        btnAlumnos.setBorder(BorderFactory.createLineBorder(Color.GRAY, 2, true)); // true para bordes redondeados
        
        
        // Usar un borde redondeado personalizado con el setBorderPainted para evitar bordes planos
        btnAlumnos.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(Color.GRAY, 2, true),
                BorderFactory.createEmptyBorder(15, 15, 15, 15)
        ));
//        try {
//            UIManager.setLookAndFeel(new FlatLightLaf());
//        } catch (UnsupportedLookAndFeelException e) {
//            e.printStackTrace();
//        }
        

        
              
    }
    
    
//    private void gifRedimension(){
//       
//        //C:\\Users\\silvia
//        
//        ImageIcon gifIcon = new ImageIcon(getClass().getResource("/img/birrete.gif"));
//        
//                if (gifIcon.getImageLoadStatus() == MediaTracker.ERRORED) {
//        System.out.println("Error al cargar el GIF");
//        return;
//    }
//        
//        
//        // Obtener la imagen desde el ImageIcon
//        Image gifImage = gifIcon.getImage();
//        
//
//
//        // Redimensionar la imagen al tamaño deseado (ancho y alto en píxeles)
//        Image resizedGif = gifImage.getScaledInstance(110, 80, Image.SCALE_DEFAULT);
//
//        // Crear un nuevo ImageIcon con la imagen redimensionada
//        ImageIcon resizedIcon = new ImageIcon(resizedGif);
//        
//        btnAlumnos = new JButton(resizedIcon);
//        
//        this.add(btnAlumnos); // 'this' debería ser tu JFrame o JPanel
//
//// Asegúrate de actualizar el contenedor si es necesario
//this.revalidate();
//this.repaint();
//    }
    
    

}
